### Create a new user
POST http://localhost:3000/violation/create
content-type: application/json

{
  "civilId": "123456789",
  "alcoholicLevel": 21,
  "transportationMean": 2,
  "fineAmount": 100000,
  "created": "123"
}

### get all violation
GET http://localhost:3000/violation/getAllViolation
